### ISSUE TITLE
Tests from AIO image are not producing logs or graphs.

### ISSUE THREAD

**Issue by pdschandler** [wallnerryan/fio-tools#2]
I'm running RancherOS with ZFS and attempting to use this tool. The tests perform succesfully, but no logs are placed in the temporary data folder at all. This means no graphs are generated either.

Here is my docker run command:
```
docker run \
-p 8001:8000 \
-v /mnt/my/custom/directory/fio:/tmp/fio-data \
-v /mnt/DRIVE1:/mnt/DRIVE1 \
-e REMOTEFILES="https://gitlab.com/myuser/fio/raw/master/generic-seq.fio" \
-e JOBFILES=generic-seq.fio \
-e PLOTNAME=generic-seq \
-d --name generic-seq clusterhq/fiotools-aio
```

Here are the contents of the .fio jobfile above:
```
[global]
name=generic-seq
filename=generic-seq
rw=rw
rwmixread=60
rwmixwrite=40
bs=256K
direct=0
numjobs=4
time_based=1
runtime=900
directory=/mnt/DRIVE1

[file1]
size=10G
ioengine=libaio
iodepth=16
```

I've substituted 'myuser' in the GitLab URL for my own obviously.

Logs aren't placed in the /tmp/fio-data folder as I assume they're meant to be. So I naturally see these errors in the container logs:
```
No log file found with pattern *_bw*!
No log file found with pattern *_iops*!
```

Thank you for creating this - it should make my upcoming disk tests a lot easier :)

**Comment by pdschandler** [comment]
After checking more fio documentation and examples I discovered that adding a name for the logfile resolves the issue:
```
write_bw_log=generic-seq.results
write_iops_log=generic-seq.results
```
This might be worth building in a default for, so the image can work with any jobfile OOTB :)

**Comment by wallnerryan** [comment]
thanks @pdschandler ! please open an issue to for default name conventions. its a good catch. Also, ive recently updated this codebase to use a newer version of FIO and a few other tweaks. please see https://github.com/portworx/fio-tools 

To use this image pull `wallnerryan/fiotools-aio` instead of `clusterhq/fiotools-aio`

**Comment by wallnerryan** [comment]
actually looks up to date here, but still use  `wallnerryan/fiotools-aio` instead of `clusterhq/fiotools-aio` to get latest build
